### PR TITLE
[DO NOT MERGE] oc-require-component

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

- a 1st attempt to start breaking down `oc-client` into components

## Coverage report

screen shot 2017-05-10 at 6 13 40 pm

### CODE REVIEW

**Comment by mattiaerre** [comment]
FYI @matteofigus @nickbalestra

**Comment by matteofigus** [comment]
❤️ this

**Comment by mattiaerre** [comment]
@matteofigus let's keep this in mind when we start working on refactoring `oc-client`, again snapshot testing is really cool also in this kind of contexts.

**Comment by matteofigus** [comment]
Question. You are doing es6 with client-side code. This means you need a build task to transpile it?

**Comment by mattiaerre** [comment]
@matteofigus yes for sure 😉 do you think this might be a problem?

**Comment by matteofigus** [comment]
no, just asking ;)

**Comment by mattiaerre** [comment]
closing but keeping the branch

**Pull request closed without merging**
