### PR TITLE
oc-my-next-run

### PR DESCRIPTION
**Pull request by mattiaerre**
# Description

screen shot 2017-03-18 at 22 31 30

### CODE REVIEW

**Comment by mattiaerre** [comment]
// cc @matteofigus @nickbalestra

**Comment by mattiaerre** [comment]
w/ SSR & `styled-components`

// cc @mxstbr

**Comment by matteofigus** [comment]
Yes! Love styled components, that's a very good spike 👍

**Comment by mattiaerre** [comment]
next, I am going to try also [jest-styled-components](https://github.com/styled-components/jest-styled-components)

// cc @MicheleBertoli

**Comment by mattiaerre** [comment]
soooo nice!
me ❤️  this 😊 

```javascript
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Title 1`] = `


.kbYEP {
  font-size: 1.5em;
  text-align: center;
}

<h1
  className="sc-bdVaJa kbYEP"
>
  Hello from oc-my-next-run Title
</h1>
`;

exports[`Wrapper 1`] = `


.bOYEsa {
  padding: 2em;
  background: floralwhite;
  font-family: monospace;
  border: 1px solid grey;
}

<section
  className="sc-bwzfXH bOYEsa"
>
  Hello from oc-my-next-run Wrapper
</section>
`;
```

// cc @matteofigus @mxstbr @MicheleBertoli

**Comment by MicheleBertoli** [comment]
Thanks for trying it with SC v2, I'm happy you like it :)
I can see two extra empty lines at the top of the snapshot, I'll investigate and fix it.

**Comment by mattiaerre** [comment]
@MicheleBertoli  perfectionist 😅

**Comment by mattiaerre** [comment]
what do you think about this @scottlepich ?

**Pull request merged**
